// <auto-generated />
using System;
using Api_net_core_8.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_net_core_8.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api_net_core_8.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "قوطی روغن نباطی",
                            MaxSpeed = 120,
                            Name = "پراید"
                        },
                        new
                        {
                            Id = 2,
                            Description = "دیوار دفاعی",
                            MaxSpeed = 110,
                            Name = "پیکان"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            MaxSpeed = 220,
                            Name = "پرشیا"
                        });
                });

            modelBuilder.Entity("Api_net_core_8.Models.Pc.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.ToTable("Pc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionId = 1,
                            Name = "G1"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionId = 2,
                            Name = "G2"
                        });
                });

            modelBuilder.Entity("Api_net_core_8.Models.Pc.PcCpu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PcFanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PcFanId");

                    b.ToTable("PcCpu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "2023",
                            Name = "I9 13900K",
                            PcFanId = 1
                        },
                        new
                        {
                            Id = 2,
                            Model = "2024",
                            Name = "I9 14900K",
                            PcFanId = 1
                        });
                });

            modelBuilder.Entity("Api_net_core_8.Models.Pc.PcDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherBord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PcCpuId")
                        .HasColumnType("int");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PcCpuId");

                    b.ToTable("PcDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "سه تا صد گونی هزار",
                            MotherBord = "sd10",
                            PcCpuId = 1,
                            Power = "120W",
                            Ram = "1GB"
                        },
                        new
                        {
                            Id = 2,
                            Description = "قول مرحله اخر",
                            MotherBord = "zf10",
                            PcCpuId = 2,
                            Power = "2300W",
                            Ram = "200GB"
                        });
                });

            modelBuilder.Entity("Api_net_core_8.Models.Pc.PcFan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PcFan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "MASTERLIQUID ML360L V2 ARGB",
                            Name = "MASTERLIQUID"
                        });
                });

            modelBuilder.Entity("Api_net_core_8.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "soheil0910line@gmail.com",
                            Family = "Robaty",
                            Name = "soheil",
                            Password = "1234",
                            UserName = "soheil0910"
                        },
                        new
                        {
                            Id = 2,
                            Family = "Robaty",
                            Name = "ali",
                            Password = "1234",
                            UserName = "ali001"
                        });
                });

            modelBuilder.Entity("Api_net_core_8.Models.Pc.PC", b =>
                {
                    b.HasOne("Api_net_core_8.Models.Pc.PcDetails", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId");

                    b.Navigation("Description");
                });

            modelBuilder.Entity("Api_net_core_8.Models.Pc.PcCpu", b =>
                {
                    b.HasOne("Api_net_core_8.Models.Pc.PcFan", "Fan")
                        .WithMany()
                        .HasForeignKey("PcFanId");

                    b.Navigation("Fan");
                });

            modelBuilder.Entity("Api_net_core_8.Models.Pc.PcDetails", b =>
                {
                    b.HasOne("Api_net_core_8.Models.Pc.PcCpu", "PcCpu")
                        .WithMany()
                        .HasForeignKey("PcCpuId");

                    b.Navigation("PcCpu");
                });
#pragma warning restore 612, 618
        }
    }
}
